create database Gescolar;
use GESCOLAR;

CREATE TABLE ALUNO (
    ID INT AUTO_INCREMENT,
    NOME VARCHAR(255),
    DATA_NASCIMENTO DATE,
    SEXO CHAR(1),
    GENERO VARCHAR(255),
    CPF CHAR(11),
    CIDADE VARCHAR(100),
    ESTADO CHAR(2),
    BAIRRO VARCHAR(150),
    RUA VARCHAR(100),
    CEP CHAR(8),
    PRIMARY KEY(ID)
);

CREATE TABLE CURSO(
    ID INT AUTO_INCREMENT,
    NOME VARCHAR(150),
    PRIMARY KEY(ID)
);

CREATE TABLE TURMA(
    ID INT  AUTO_INCREMENT,
    ID_CURSO INT,
    DESCRICAO VARCHAR(50),
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_CURSO) REFERENCES CURSO (ID)
);